services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Lemming\PageTreeFilter\:
    resource: '../Classes/*'

  Lemming\PageTreeFilter\Controller\NewContentElementController:
    public: true